name: Release

on:
  push:
    branches:
      - main

env:
  ACTION_NAME: kustomize-deploy-action

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          skip-github-pull-request: true
      - uses: actions/checkout@v4
      - name: Tag major and minor versions in Git
        if: ${{ steps.release.outputs.release_created }}
        uses: jacobsvante/tag-major-minor-action@v0
        with:
          major: ${{ steps.release.outputs.major }}
          minor: ${{ steps.release.outputs.minor }}
